// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://smartattendance.fastwebcm.local/api/v1' | (string & {});
};

export type UserType = 'student' | 'staff';

export type UserStatus = 'active' | 'inactive' | 'dismissed';

export type BiometricEnrollmentStatus = 'pending' | 'completed';

export type Login = {
    username: string;
    password: string;
    stayloggedin?: boolean;
};

export type LoginResponse = {
    success?: boolean;
    accessToken?: string;
    user?: {
        id?: number;
        role?: string;
        username?: string;
        email?: string;
    };
};

export type PaginationMeta = {
    /**
     * Total quantity of active users matching structural selection metrics.
     */
    total_records: number;
    /**
     * The currently pulled response page offset iteration.
     */
    current_page: number;
    /**
     * Maximum aggregate count of dynamic pagination user slices available.
     */
    total_pages: number;
    /**
     * Total boundary count constraint cap assigned for user blocks.
     */
    limit: number;
};

export type AttendanceLedgerData = {
    /**
     * Dense array list charting explicit day configurations within targeted window frames.
     */
    calendarDates: Array<{
        raw?: string;
        label?: string;
        isWeekend?: boolean;
        dayName?: string;
        exact_date?: string;
    }>;
    /**
     * Array of global infrastructure anomalies or holiday closures falling inside the matrix.
     */
    exceptions: Array<{
        date?: string;
        name?: string;
        type?: string;
    }>;
    /**
     * Page-sliced listing of physical user entities rendered downstream inside row tracks.
     */
    users: Array<{
        id?: number;
        name?: string;
        role?: string;
        regno?: string;
        avatarColor?: string;
    }>;
    /**
     * Intertwined chronological cross-reference card layout tracking user summary performance maps.
     */
    initialAttendanceSummary: Array<{
        id?: number | null;
        /**
         * Maps explicitly back to the unique tracking user id.
         */
        employee_id?: number;
        date?: string;
        event_id?: number;
        first_checkin?: string | null;
        last_checkout?: string | null;
        total_hours?: number;
        checkin_status?: 'on time' | 'late' | 'absent';
        session_status?: 'active' | 'completed' | 'missed_checkout' | 'no_show';
        attendance_status?: 'present' | 'absent' | 'on permission';
        derived_from_session?: 0 | 1;
        /**
         * Lateness value deviation tracked directly in minutes.
         */
        variance?: number;
    }>;
    metrics?: {
        /**
         * Total count of late arrivals recorded across the entire user base for the specified period.
         */
        total_late?: number;
        total_missed_checkout?: number;
        total_audit_override?: number;
    };
};

export type User = {
    id?: number;
    fname: string;
    lname: string;
    email: string;
    gender?: 'male' | 'female';
    user_type: UserType;
    status?: UserStatus;
    biometric_enrollment_status?: BiometricEnrollmentStatus;
    /**
     * role id for privileged staff
     */
    role_id?: number;
    /**
     * current class of the student
     */
    class_id?: number;
    regno?: string;
    username?: string;
    password?: string;
};

export type UserCreate = User;

export type UserResponse = {
    id?: number;
    name?: string;
    email?: string;
    gender?: 'male' | 'female';
    status?: UserStatus;
    biometric_enrollment_status?: BiometricEnrollmentStatus;
    role?: string;
    class?: string;
    studentregno?: string;
    username?: string;
};

export type StudentInput = {
    /**
     * The online database studentid.
     */
    id: number;
    /**
     * Unique registration number.
     */
    sregnum: string;
    fname: string;
    lname: string;
    gender: 'Male' | 'Female' | 'Other';
    /**
     * The class name string.
     */
    cname: string;
};

export type StaffInput = {
    /**
     * The online database teacherid.
     */
    id: number;
    /**
     * Unique teacher registration number.
     */
    tregnum: string;
    fname: string;
    lname: string;
};

export type SyncRequest = {
    students?: Array<StudentInput>;
    staff?: Array<StaffInput>;
};

export type SyncResponse = {
    success?: boolean;
    /**
     * List of student IDs successfully processed to be sent back to online ACK.
     */
    studentIds?: Array<number>;
    /**
     * List of teacher IDs successfully processed to be sent back to online ACK.
     */
    staffIds?: Array<number>;
};

export type Role = {
    role_name: string;
    description?: string;
};

export type RoleResponse = Role & {
    id?: number;
};

export type Branch = {
    name: string;
    location?: string;
    description?: string;
    status?: 'active' | 'inactive';
};

export type BranchResponse = Branch & {
    id?: number;
    /**
     * Branch admins
     */
    admin_id?: Array<number>;
    date_created?: string;
};

export type Group = {
    branch_id: number;
    grouptype_id: number;
    name: string;
    expected_weekly_hours?: number;
    absence_threshold: number;
    supervisors?: Array<{
        user_id?: number;
    }>;
};

export type GroupResponse = Group & {
    id?: number;
    date_created?: string;
};

export type Subgroup = {
    group_id: number;
    name: string;
    absence_threshold: number;
    created_by?: number;
};

export type SubgroupResponse = Subgroup & {
    id?: number;
    date_created?: string;
};

export type PermissionRequest = {
    permissiontype_id?: number;
    user_id?: number;
    /**
     * The admin or HR who initiated this permission
     */
    initiatedby?: number;
    reason?: string;
    start_date?: string;
    end_date?: string;
    status?: 'pending' | 'approved' | 'rejected';
    /**
     * The stored file name (optional)
     */
    additional_proof?: string;
    requested_at?: string;
};

export type PermissionApproval = {
    permission_id?: number;
    approver_id?: number;
    remark?: string;
    status?: 'pending' | 'approved' | 'rejected';
};

export type Annoucement = {
    name?: string;
    message?: string;
    /**
     * The date, time the annoucement will be visible to its respective groups/subgroups - terminals
     */
    start_datetime?: string;
    /**
     * The date, time the annoucement will be disappear to its respective groups/subgroups - terminals
     */
    end_datetime?: string;
    /**
     * The admin who created the announcement
     */
    created_by?: number;
};

export type AnnouncementResponse = Annoucement & {
    id?: number;
    date_created?: string;
};

export type Event = {
    name?: string;
    start_datetime?: string;
    end_datetime?: string;
    affects_attendance?: string;
    /**
     * '1' = check-in only
     * '2' = check-in and check-out
     *
     */
    handshake?: '1' | '2';
    /**
     * User who created the event, optional
     */
    created_by?: number;
};

export type EventCheckinCheckoutRange = {
    checkin_start_datetime?: string;
    checkin_end_datetime?: string;
    checkout_start_datetime?: string | null;
    checkout_end_datetime?: string | null;
};

/**
 * groups/subgroups allowed to auth for this event and the auth mode(s)
 */
export type EventAccessPolicy = {
    group_id?: number;
    subgroup_id?: number;
    auth_type_id?: number;
};

export type EventCreate = Event & {
    /**
     * check-in/check-out range for this event
     */
    check_in_out_range?: Array<EventCheckinCheckoutRange>;
    access_policy?: Array<EventAccessPolicy>;
};

export type EventResponse = Event & {
    id?: number;
    created_at?: string;
    access_policy?: Array<EventAccessPolicy & {
        id?: number;
        group_name?: string;
        auth_type_name?: string;
    }>;
    checkin_checkout_ranges?: EventCheckinCheckoutRange & {
        id?: number;
    };
};

export type Exception = {
    title: string;
    exception_type: 'public_holiday' | 'company_event' | 'system_maintenance' | 'emergency_closure' | 'term_closure' | 'other';
    description?: string;
    start_date: string;
    end_date: string;
    /**
     * The admin who created the exception
     */
    created_by?: number;
};

export type ExceptionUpsertRequest = Exception & {
    /**
     * Required for update, auto generated for create
     */
    id?: number;
};

export type ExceptionResponse = ExceptionUpsertRequest & {
    created_by_name?: string;
};

export type Terminal = {
    id?: number | null;
    name?: string;
    /**
     * Auto generated by the system
     */
    activation_code?: string;
    branch_id?: number;
    slug?: string;
    status?: 'pending' | 'active' | 'revoked';
};

export type AuthTypes = {
    id?: number;
    name?: 'face' | 'fingerprint' | 'card';
};

/**
 * This defines the type of auth supported by the terminal
 */
export type TerminalCapabilities = {
    /**
     * reference to the terminal auth types
     */
    auth_type_id: number;
    auth_step: number;
};

/**
 * groups/subgroups allowed to auth at this terminal
 */
export type TerminalAccessPolicy = {
    group_id?: number | null;
    subgroup_id?: number | null;
    auth_type_id?: number;
};

export type TerminalCreate = {
    terminalDetails?: Terminal & {
        [key: string]: unknown;
    };
    /**
     * The supported auth types for this terminal
     */
    authCapabilities?: Array<TerminalCapabilities>;
    authPolicies?: Array<TerminalAccessPolicy>;
};

export type TerminalUpsertResponse = Terminal & {
    success?: boolean;
    message?: string;
    /**
     * Auto generated by the system
     */
    activationCode?: string;
};

export type TerminalFetchResponse = {
    id: number;
    name: string;
    branch_id: number;
    slug?: string;
    branch: string;
    status: 'active' | 'inactive';
    ip_address: string | null;
    last_heartbeat: string | null;
    health_status: string;
    auth_capabilities?: Array<TerminalCapabilities & {
        terminal_id?: number;
        auth_type_name?: 'face' | 'fingerprint' | 'card';
    }>;
    access_policy?: Array<TerminalAccessPolicy & {
        id?: number;
        terminal_id?: number;
        created_at?: string;
        updated_at?: string | null;
        group_name?: string;
        auth_type_name?: 'face' | 'fingerprint' | 'card';
    }>;
};

export type ApiResponseTerminalList = {
    success: boolean;
    data: Array<TerminalFetchResponse>;
};

export type BiometricFaceEnrollRequest = {
    user_id: number;
    /**
     * Base64 encoded face image
     */
    face_image: string;
};

export type BiometricFaceEnrollResponse = {
    message: string;
    biometric_profile_id: number;
};

export type BiometricFaceVerifyRequest = {
    terminal_id: number;
    face_image: string;
};

export type BiometricFaceVerifyResponse = {
    matched: boolean;
    user_id?: number | null;
    confidence_score?: number;
    message?: string;
};

export type AttendanceStatus = {
    name?: 'present' | 'absent' | 'late' | 'on permission';
};

/**
 * track progress throughout the auth sequence
 */
export type TerminalAuthSession = {
    user_id?: number;
    terminal_id?: number;
    /**
     * Since most terminals are presummed to support atleast 2 auth types,
     * the current step will help track the progress to ensure that the user completes all the terminal required auth types
     * before there are dimmed to have completed an auth session( check-in or check-out)
     *
     */
    current_step?: number;
    status?: 'in_progress' | 'completed';
};

/**
 * logs each auth attemp, ie record is created for each completed auth session
 */
export type TerminalAuthLog = {
    user_id?: number;
    terminal_id?: number;
    attendance_context?: 'daily' | 'event';
    event_id?: number;
    auth_type_id?: number;
};

/**
 * Represents attendance after auth successs
 * ie upon successfull checkin and checkout for daily attendance
 * or checkin and/or checkout for event attendance depending on the handshake
 *
 */
export type TerminalAttendanceSession = {
    user_id?: number;
    terminal_id?: number;
    attendance_context?: 'daily' | 'event';
    event_id?: number;
    checkin_timestamp?: string;
    checkout_timestamp?: string;
    checkin_status?: 'on time' | 'late';
    checkout_status?: 'on time' | 'early';
    session_status?: 'active' | 'completed' | 'missed checkout';
    sync_status?: 'pending' | 'synced' | 'error';
};

/**
 * Summary of the daily/event attendance, this is the record that get sync to the central db
 * Was the user present, late or on permission for this day
 *
 */
export type TerminalAttendanceSummary = {
    user_id?: number;
    terminal_id?: number;
    attendance_date?: string;
    attendance_context?: 'daily' | 'event';
    event_id?: number;
    first_checkin?: string;
    last_checkout?: string;
    /**
     * Time difference in int btn last checkout and first checkin
     */
    total_hours?: number;
    attendance_status?: number;
    /**
     * useful when the user is on a permission, so we do not have to compute the attendance session to arive to get the summary
     */
    derived_from_session?: boolean;
};

export type TerminalAuthCreate = TerminalAuthSession & {
    terminal_auth_log?: TerminalAuthLog & {
        [key: string]: unknown;
    };
};

export type TerminalAuthInProgressResponse = {
    status: 'in_progress';
    current_step: number;
    next_auth_type_id: number;
};

export type TerminalAuthCompletedResponse = {
    status: 'completed';
    message?: string;
    attendance_session: TerminalAttendanceSession;
};

export type TerminalAttendanceSummaryCreate = TerminalAttendanceSummary & {
    [key: string]: unknown;
};

export type LogEntry = {
    id?: number;
    category?: string;
    log_level?: string;
    description?: string;
    ip_address?: string;
    request_uri?: string;
    /**
     * Dynamic data snapshot properties dependent on context origin type (e.g., action types, trace stack, parameters).
     */
    context_data?: {
        [key: string]: unknown;
    } | null;
    date_created?: string;
    name?: string | null;
    role_name?: string | null;
};

export type LoginData = {
    body: Login;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type LoginResponses = {
    /**
     * successful login
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type LogoutResponses = {
    /**
     * logout successful
     */
    200: {
        success?: boolean;
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type RefreshResponses = {
    /**
     * refresh access token
     */
    200: LoginResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by user type
         */
        user_type?: UserType;
        /**
         * Filter by status
         */
        status?: UserStatus;
    };
    url: '/api/v1/users';
};

export type ListUsersErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListUsersResponses = {
    /**
     * List of users
     */
    200: Array<UserResponse>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    /**
     * Ensure you insert into staff tbl specifying the role and of the staff if the user type is staff
     */
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type CreateUserErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateUserResponses = {
    /**
     * User created successfully
     */
    201: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type SyncUsersData = {
    body: SyncRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/sync';
};

export type SyncUsersErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type SyncUsersResponses = {
    /**
     * Users synced successfully
     */
    200: SyncResponse;
};

export type SyncUsersResponse = SyncUsersResponses[keyof SyncUsersResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type DeleteUserErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type DeleteUserResponses = {
    /**
     * User deleted successfully
     */
    200: unknown;
};

export type GetUserByIdData = {
    body?: never;
    path: {
        /**
         * The unique ID of the user
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type GetUserByIdErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetUserByIdResponses = {
    /**
     * User found
     */
    200: UserResponse;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type UpdateUserData = {
    body: UserCreate;
    path: {
        /**
         * The unique ID of the user
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type UpdateUserErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type UpdateUserResponses = {
    /**
     * User updated successfully
     */
    200: UserResponse;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ListRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/roles';
};

export type ListRolesErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListRolesResponses = {
    /**
     * Roles list
     */
    200: Array<RoleResponse>;
};

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses];

export type ListBranchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/branches';
};

export type ListBranchesErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListBranchesResponses = {
    /**
     * List of branches
     */
    200: Array<BranchResponse>;
};

export type ListBranchesResponse = ListBranchesResponses[keyof ListBranchesResponses];

export type CreateBranchData = {
    body: Branch & {
        /**
         * branch admin
         */
        user_id?: number;
    };
    path?: never;
    query?: never;
    url: '/api/v1/branches';
};

export type CreateBranchErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateBranchResponses = {
    /**
     * Branch created successfully
     */
    201: BranchResponse;
};

export type CreateBranchResponse = CreateBranchResponses[keyof CreateBranchResponses];

export type UpdateBranchData = {
    body?: Branch & {
        user_id?: number;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/branches/{id}';
};

export type UpdateBranchErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type UpdateBranchResponses = {
    /**
     * Branch updated successfully
     */
    200: unknown;
};

export type CreateGroupTypeData = {
    body: {
        name: string;
        abbreviation?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/groups/group_type';
};

export type CreateGroupTypeErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateGroupTypeResponses = {
    /**
     * Group type created successfully
     */
    201: unknown;
};

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/groups';
};

export type ListGroupsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListGroupsResponses = {
    /**
     * Groups list
     */
    200: Array<GroupResponse>;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
    body: Group;
    path?: never;
    query?: never;
    url: '/api/v1/groups';
};

export type CreateGroupErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateGroupResponses = {
    /**
     * Group created
     */
    201: unknown;
};

export type AssignUsersToGroupData = {
    body?: {
        group_id?: number;
        user_ids?: Array<number>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/groups/members';
};

export type AssignUsersToGroupErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type AssignUsersToGroupResponses = {
    /**
     * Users assigned to group
     */
    200: unknown;
};

export type ListSubgroupsData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/api/v1/groups/{groupId}/subgroups';
};

export type ListSubgroupsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListSubgroupsResponses = {
    /**
     * Subgroup list
     */
    200: unknown;
};

export type CreateSubgroupData = {
    body?: Subgroup;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/api/v1/groups/{groupId}/subgroups';
};

export type CreateSubgroupErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateSubgroupResponses = {
    /**
     * Subgroup created
     */
    201: unknown;
};

export type AssignUsersToSubgroupData = {
    body?: {
        subgroup_id?: number;
        user_ids?: Array<number>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/subgroups/member';
};

export type AssignUsersToSubgroupErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type AssignUsersToSubgroupResponses = {
    /**
     * Users assigned to subgroup
     */
    200: unknown;
};

export type CreatePermissionRequestData = {
    body: PermissionRequest & {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/permissions';
};

export type CreatePermissionRequestErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreatePermissionRequestResponses = {
    /**
     * Permission request created
     */
    201: unknown;
};

export type DecidePermissionRequestData = {
    body: PermissionApproval & {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/permissions/decision';
};

export type DecidePermissionRequestErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type DecidePermissionRequestResponses = {
    /**
     * Permission decision recorded
     */
    200: unknown;
};

export type ListAnnouncementsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If provided, returns pending announcements for the specified group.
         */
        group_id?: number;
        /**
         * If provided, returns pending announcements for the specified subgroup.
         */
        subgroup_id?: number;
    };
    url: '/api/v1/announcement';
};

export type ListAnnouncementsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListAnnouncementsResponses = {
    /**
     * List of events (optionally filtered by group or subgroup)
     */
    200: Array<AnnouncementResponse>;
};

export type ListAnnouncementsResponse = ListAnnouncementsResponses[keyof ListAnnouncementsResponses];

export type CreateAnnouncementData = {
    body: Annoucement & {
        /**
         * Target groups
         */
        group_id: Array<number>;
        /**
         * Target subgroups
         */
        subgroup_id: Array<number>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/announcement';
};

export type CreateAnnouncementErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateAnnouncementResponses = {
    /**
     * Annoucement created successfully
     */
    200: unknown;
};

export type ListEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If provided, returns pending events for the specified group.
         */
        group_id?: number;
        /**
         * If provided, returns pending events for the specified subgroup.
         */
        subgroup_id?: number;
    };
    url: '/api/v1/events';
};

export type ListEventsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListEventsResponses = {
    /**
     * List of events (optionally filtered by group or subgroup)
     */
    200: Array<EventResponse>;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type CreateEventData = {
    body: EventCreate;
    path?: never;
    query?: never;
    url: '/api/v1/events';
};

export type CreateEventErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateEventResponses = {
    /**
     * Event created successfully
     */
    200: unknown;
};

export type DeleteEventData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/events/{id}';
};

export type DeleteEventErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type DeleteEventResponses = {
    /**
     * Event deleted successfully
     */
    200: unknown;
};

export type OneExceptionData = {
    body?: never;
    path?: never;
    query: {
        id: number;
    };
    url: '/api/v1/exceptions';
};

export type OneExceptionErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type OneExceptionResponses = {
    /**
     * List of exceptions
     */
    200: Array<ExceptionResponse>;
};

export type OneExceptionResponse = OneExceptionResponses[keyof OneExceptionResponses];

export type CreateExceptionData = {
    body: ExceptionUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/v1/exceptions';
};

export type CreateExceptionErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateExceptionResponses = {
    /**
     * Exception created successfully
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type CreateExceptionResponse = CreateExceptionResponses[keyof CreateExceptionResponses];

export type ListExceptionsData = {
    body?: never;
    path?: never;
    query?: {
        exception_type?: 'public_holiday' | 'company_event' | 'system_maintenance' | 'emergency_closure' | 'term_closure' | 'other';
    };
    url: '/api/v1/exceptions/all';
};

export type ListExceptionsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListExceptionsResponses = {
    /**
     * List of exceptions
     */
    200: {
        success?: boolean;
        data?: Array<ExceptionResponse>;
    };
};

export type ListExceptionsResponse = ListExceptionsResponses[keyof ListExceptionsResponses];

export type DeleteExceptionData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/exceptions/{id}';
};

export type DeleteExceptionErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type DeleteExceptionResponses = {
    /**
     * Exception deleted successfully
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type DeleteExceptionResponse = DeleteExceptionResponses[keyof DeleteExceptionResponses];

export type ListTerminalsData = {
    body?: never;
    path?: never;
    query?: {
        branch_id?: number;
        terminal_id?: number;
        status?: 'active' | 'pending' | 'revoked';
    };
    url: '/api/v1/terminal';
};

export type ListTerminalsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListTerminalsResponses = {
    /**
     * List of all terminals at that branch
     */
    200: ApiResponseTerminalList;
};

export type ListTerminalsResponse = ListTerminalsResponses[keyof ListTerminalsResponses];

export type CreateTerminalData = {
    body: TerminalCreate;
    path?: never;
    query?: never;
    url: '/api/v1/terminal';
};

export type CreateTerminalErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateTerminalResponses = {
    /**
     * Terminal created successfully
     */
    200: TerminalUpsertResponse;
};

export type CreateTerminalResponse = CreateTerminalResponses[keyof CreateTerminalResponses];

export type UpdateTerminalData = {
    body: TerminalCreate;
    path?: never;
    query?: never;
    url: '/api/v1/terminal';
};

export type UpdateTerminalErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type UpdateTerminalResponses = {
    /**
     * Terminal created successfully
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type UpdateTerminalResponse = UpdateTerminalResponses[keyof UpdateTerminalResponses];

export type DeleteTerminalData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/terminal/{id}';
};

export type DeleteTerminalErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type DeleteTerminalResponses = {
    /**
     * Delete terminal successfully
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type DeleteTerminalResponse = DeleteTerminalResponses[keyof DeleteTerminalResponses];

export type GetTerminalBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/terminal/slug/{slug}';
};

export type GetTerminalBySlugErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetTerminalBySlugResponses = {
    /**
     * Terminal details
     */
    200: TerminalCreate;
};

export type GetTerminalBySlugResponse = GetTerminalBySlugResponses[keyof GetTerminalBySlugResponses];

export type TerminalAuthData = {
    body: TerminalAuthCreate;
    path?: never;
    query?: never;
    url: '/api/v1/terminals/auth';
};

export type TerminalAuthErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type TerminalAuthResponses = {
    /**
     * Authentication successful, if there are more auth types to complete, the response will indicate
     */
    200: TerminalAuthInProgressResponse | TerminalAuthCompletedResponse;
};

export type TerminalAuthResponse = TerminalAuthResponses[keyof TerminalAuthResponses];

export type GetAttendanceLedgerData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter range starting date (YYYY-MM-DD). Defaults to 4 days ago from today.
         */
        start_date?: string;
        /**
         * Filter range ending date (YYYY-MM-DD). Defaults to the current date.
         */
        end_date?: string;
        /**
         * Optional filter matching specific core attendance summary log status profiles.
         */
        status?: string;
        /**
         * The horizontal page index slice targeted for active users pagination chunks.
         */
        page?: number;
        /**
         * Total horizontal record count bounds limit of users isolated to return per request page.
         */
        limit?: number;
        /**
         * Attendance context filter daily or event default is daily",
         */
        context?: 'daily' | 'event';
        search?: string;
    };
    url: '/api/v1/attendance/ledger';
};

export type GetAttendanceLedgerErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetAttendanceLedgerResponses = {
    /**
     * Attendance matrix dataset generated successfully
     */
    200: {
        success?: boolean;
        data?: AttendanceLedgerData;
        meta?: PaginationMeta;
    };
};

export type GetAttendanceLedgerResponse = GetAttendanceLedgerResponses[keyof GetAttendanceLedgerResponses];

export type GetUserAttendanceAnalyticsData = {
    body?: never;
    path: {
        /**
         * Unique internal primary database identifier of the target user profile.
         */
        id: number;
    };
    query?: {
        /**
         * Context tracking constraint for analytics isolating structural metrics.
         */
        context?: 'daily' | 'event';
        start_date?: string;
        end_date?: string;
        page?: number;
        limit?: number;
    };
    url: '/api/v1/attendance/user/{id}';
};

export type GetUserAttendanceAnalyticsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetUserAttendanceAnalyticsResponses = {
    /**
     * User analytics profile payload generated successfully.
     */
    200: {
        success?: boolean;
        metrics?: {
            /**
             * Adjusted target workload calendar expectations excluding granted permissions.
             */
            expected_days?: number;
            present_days?: number;
            late_arrivals?: number;
            absent_days?: number;
            permission_days?: number;
        };
        /**
         * Chronological list of user logs.
         */
        history?: Array<{
            date?: string;
            checkin?: string | null;
            checkout?: string | null;
            hours?: number;
            status?: string;
            terminal_id?: string;
            sync_status?: string;
        }>;
        meta?: PaginationMeta;
    };
};

export type GetUserAttendanceAnalyticsResponse = GetUserAttendanceAnalyticsResponses[keyof GetUserAttendanceAnalyticsResponses];

export type PartialEditAttendanceData = {
    body: {
        /**
         * The unique row identification key pointing to `tbl_attendance_summary`.
         */
        id: number;
        /**
         * The targeted administrative status classification override.
         */
        status: 'present' | 'absent' | 'on permission';
        /**
         * Number of recognized working session hours (automatically forced to 0.0 if status is absent).
         */
        hours: number;
        context?: 'daily' | 'event';
        userId?: number;
        date?: string;
        event_id?: number | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/attendance';
};

export type PartialEditAttendanceErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type PartialEditAttendanceResponses = {
    /**
     * Attendance override was successful.
     */
    200: {
        success?: boolean;
        message?: string;
        userId?: number;
    };
};

export type PartialEditAttendanceResponse = PartialEditAttendanceResponses[keyof PartialEditAttendanceResponses];

export type SyncAttendanceSummaryData = {
    body: Array<TerminalAttendanceSummaryCreate>;
    path?: never;
    query?: never;
    url: '/api/v1/attendance/sync';
};

export type SyncAttendanceSummaryErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type SyncAttendanceSummaryResponses = {
    /**
     * Attendance summary synced
     */
    200: {
        message?: string;
    } | {
        message?: string;
        failed_records?: Array<{
            user_id?: number;
            terminal_id?: number;
            attendance_date?: string;
            attendance_context?: string;
            attendance_status?: number;
            error_message?: string;
        }>;
    };
};

export type SyncAttendanceSummaryResponse = SyncAttendanceSummaryResponses[keyof SyncAttendanceSummaryResponses];

export type FaceEnrollmentData = {
    body: BiometricFaceEnrollRequest;
    path?: never;
    query?: never;
    url: '/api/v1/biometric/face/enroll';
};

export type FaceEnrollmentErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type FaceEnrollmentResponses = {
    /**
     * face enrollment successfull
     */
    200: BiometricFaceEnrollResponse;
};

export type FaceEnrollmentResponse = FaceEnrollmentResponses[keyof FaceEnrollmentResponses];

export type FaceVerificationData = {
    body: BiometricFaceVerifyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/biometric/face/verify';
};

export type FaceVerificationErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type FaceVerificationResponses = {
    /**
     * face verification result
     */
    200: BiometricFaceVerifyResponse;
};

export type FaceVerificationResponse = FaceVerificationResponses[keyof FaceVerificationResponses];

export type FetchLogsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter logs by operational category (e.g., system, error, sync, biometric).
         */
        category?: string;
        /**
         * Filter logs by severity classification.
         */
        level?: 'info' | 'warning' | 'error';
        /**
         * Restrict tracking to entries on or after this timestamp (Y-m-d or Y-m-d H:i:s).
         */
        start_date?: string;
        /**
         * Restrict tracking to entries on or before this date (automatically pads to 23:59:59 if time is omitted).
         */
        end_date?: string;
        /**
         * The current page index sequence offset indicator.
         */
        page?: number;
        /**
         * Maximum total rows to load within a singular pagination dataset frame (capped at 100).
         */
        limit?: number;
    };
    url: '/api/v1/logs';
};

export type FetchLogsErrors = {
    /**
     * Fatal backend system error or exception block dropped.
     */
    500: {
        success?: boolean;
        message?: string;
        error?: string;
    };
};

export type FetchLogsError = FetchLogsErrors[keyof FetchLogsErrors];

export type FetchLogsResponses = {
    /**
     * Logs structural matrix payload successfully retrieved.
     */
    200: {
        success?: boolean;
        message?: string;
        meta?: {
            total_records?: number;
            total_pages?: number;
            current_page?: number;
            limit?: number;
        };
        data?: Array<LogEntry>;
    };
};

export type FetchLogsResponse = FetchLogsResponses[keyof FetchLogsResponses];
