// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zUserType = z.enum(['student', 'staff']);

export const zUserStatus = z.enum([
    'active',
    'inactive',
    'dismissed'
]);

export const zBiometricEnrollmentStatus = z.enum(['pending', 'completed']);

export const zLogin = z.object({
    username: z.string(),
    password: z.string().min(6),
    stayloggedin: z.optional(z.boolean())
});

export const zLoginResponse = z.object({
    success: z.optional(z.boolean()),
    accessToken: z.optional(z.string()),
    user: z.optional(z.object({
        id: z.optional(z.int()),
        role: z.optional(z.string()),
        username: z.optional(z.string()),
        email: z.optional(z.string())
    }))
});

export const zPaginationMeta = z.object({
    total_records: z.int(),
    current_page: z.int(),
    total_pages: z.int(),
    limit: z.int()
});

export const zAttendanceLedgerData = z.object({
    calendarDates: z.array(z.object({
        raw: z.optional(z.iso.date()),
        label: z.optional(z.string()),
        isWeekend: z.optional(z.boolean()),
        dayName: z.optional(z.string()),
        exact_date: z.optional(z.iso.date())
    })),
    exceptions: z.array(z.object({
        date: z.optional(z.iso.date()),
        name: z.optional(z.string()),
        type: z.optional(z.string())
    })),
    users: z.array(z.object({
        id: z.optional(z.int()),
        name: z.optional(z.string()),
        role: z.optional(z.string()),
        regno: z.optional(z.string()),
        avatarColor: z.optional(z.string())
    })),
    initialAttendanceSummary: z.array(z.object({
        id: z.optional(z.union([
            z.int(),
            z.null()
        ])),
        employee_id: z.optional(z.int()),
        date: z.optional(z.iso.date()),
        event_id: z.optional(z.int()),
        first_checkin: z.optional(z.union([
            z.iso.datetime(),
            z.null()
        ])),
        last_checkout: z.optional(z.union([
            z.iso.datetime(),
            z.null()
        ])),
        total_hours: z.optional(z.number()),
        checkin_status: z.optional(z.enum([
            'on time',
            'late',
            'absent'
        ])),
        session_status: z.optional(z.enum([
            'active',
            'completed',
            'missed_checkout',
            'no_show'
        ])),
        attendance_status: z.optional(z.enum([
            'present',
            'absent',
            'on permission'
        ])),
        derived_from_session: z.optional(z.union([z.literal(0), z.literal(1)])),
        variance: z.optional(z.int())
    })),
    metrics: z.optional(z.object({
        total_late: z.optional(z.int()),
        total_missed_checkout: z.optional(z.int()),
        total_audit_override: z.optional(z.int())
    }))
});

export const zUser = z.object({
    id: z.optional(z.int()),
    fname: z.string(),
    lname: z.string(),
    email: z.string(),
    gender: z.optional(z.enum(['male', 'female'])),
    user_type: zUserType,
    status: z.optional(zUserStatus),
    biometric_enrollment_status: z.optional(zBiometricEnrollmentStatus),
    role_id: z.optional(z.int()),
    class_id: z.optional(z.int()),
    regno: z.optional(z.string()),
    username: z.optional(z.string()),
    password: z.optional(z.string())
});

export const zUserCreate = zUser;

export const zUserResponse = z.object({
    id: z.optional(z.int()),
    name: z.optional(z.string()),
    email: z.optional(z.string()),
    gender: z.optional(z.enum(['male', 'female'])),
    status: z.optional(zUserStatus),
    biometric_enrollment_status: z.optional(zBiometricEnrollmentStatus),
    role: z.optional(z.string()),
    class: z.optional(z.string()),
    studentregno: z.optional(z.string()),
    username: z.optional(z.string())
});

export const zStudentInput = z.object({
    id: z.int(),
    sregnum: z.string(),
    fname: z.string(),
    lname: z.string(),
    gender: z.enum([
        'Male',
        'Female',
        'Other'
    ]),
    cname: z.string()
});

export const zStaffInput = z.object({
    id: z.int(),
    tregnum: z.string(),
    fname: z.string(),
    lname: z.string()
});

export const zSyncRequest = z.object({
    students: z.optional(z.array(zStudentInput)),
    staff: z.optional(z.array(zStaffInput))
});

export const zSyncResponse = z.object({
    success: z.optional(z.boolean()),
    studentIds: z.optional(z.array(z.int())),
    staffIds: z.optional(z.array(z.int()))
});

export const zRole = z.object({
    role_name: z.string(),
    description: z.optional(z.string())
});

export const zRoleResponse = zRole.and(z.object({
    id: z.optional(z.int())
}));

export const zBranch = z.object({
    name: z.string(),
    location: z.optional(z.string()),
    description: z.optional(z.string()),
    status: z.optional(z.enum(['active', 'inactive']))
});

export const zBranchResponse = zBranch.and(z.object({
    id: z.optional(z.int()),
    admin_id: z.optional(z.array(z.int())),
    date_created: z.optional(z.iso.datetime())
}));

export const zGroup = z.object({
    branch_id: z.int(),
    grouptype_id: z.int(),
    name: z.string(),
    expected_weekly_hours: z.optional(z.int()),
    absence_threshold: z.int(),
    supervisors: z.optional(z.array(z.object({
        user_id: z.optional(z.int())
    })))
});

export const zGroupResponse = zGroup.and(z.object({
    id: z.optional(z.int()),
    date_created: z.optional(z.iso.datetime())
}));

export const zSubgroup = z.object({
    group_id: z.int(),
    name: z.string(),
    absence_threshold: z.int(),
    created_by: z.optional(z.int())
});

export const zSubgroupResponse = zSubgroup.and(z.object({
    id: z.optional(z.int()),
    date_created: z.optional(z.iso.datetime())
}));

export const zPermissionDetail = z.object({
    id: z.optional(z.int()),
    permission_type_id: z.optional(z.int()),
    permission_type_name: z.optional(z.string()),
    user_id: z.optional(z.int()),
    employee_name: z.optional(z.string()),
    initiatedby: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    reason: z.optional(z.string()),
    start_date: z.optional(z.iso.date()),
    end_date: z.optional(z.iso.date()),
    status: z.optional(z.string()),
    additional_proof: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    requested_at: z.optional(z.iso.datetime())
});

export const zPermissionExtendedRow = zPermissionDetail.and(z.object({
    initiator_name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    closing_remark: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    approver_name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    date_approved: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ]))
}));

export const zAnnoucement = z.object({
    name: z.optional(z.string()),
    message: z.optional(z.string()),
    start_datetime: z.optional(z.iso.datetime()),
    end_datetime: z.optional(z.iso.datetime()),
    created_by: z.optional(z.int())
});

export const zAnnouncementResponse = zAnnoucement.and(z.object({
    id: z.optional(z.int()),
    date_created: z.optional(z.iso.datetime())
}));

export const zEvent = z.object({
    name: z.optional(z.string()),
    start_datetime: z.optional(z.iso.datetime()),
    end_datetime: z.optional(z.iso.datetime()),
    affects_attendance: z.optional(z.string()).default('1'),
    handshake: z.optional(z.enum(['1', '2'])),
    created_by: z.optional(z.int())
});

export const zEventCheckinCheckoutRange = z.object({
    checkin_start_datetime: z.optional(z.iso.datetime()),
    checkin_end_datetime: z.optional(z.iso.datetime()),
    checkout_start_datetime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    checkout_end_datetime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ]))
});

/**
 * groups/subgroups allowed to auth for this event and the auth mode(s)
 */
export const zEventAccessPolicy = z.object({
    group_id: z.optional(z.int()),
    subgroup_id: z.optional(z.int()),
    auth_type_id: z.optional(z.int())
});

export const zEventCreate = zEvent.and(z.object({
    check_in_out_range: z.optional(z.array(zEventCheckinCheckoutRange)),
    access_policy: z.optional(z.array(zEventAccessPolicy))
}));

export const zEventResponse = zEvent.and(z.object({
    id: z.optional(z.int()),
    created_at: z.optional(z.iso.datetime()),
    access_policy: z.optional(z.array(zEventAccessPolicy.and(z.object({
        id: z.optional(z.int()),
        group_name: z.optional(z.string()),
        auth_type_name: z.optional(z.string())
    })))),
    checkin_checkout_ranges: z.optional(zEventCheckinCheckoutRange.and(z.object({
        id: z.optional(z.int())
    })))
}));

export const zException = z.object({
    title: z.string(),
    exception_type: z.enum([
        'public_holiday',
        'company_event',
        'system_maintenance',
        'emergency_closure',
        'term_closure',
        'other'
    ]),
    description: z.optional(z.string()),
    start_date: z.iso.date(),
    end_date: z.iso.date(),
    created_by: z.optional(z.int())
});

export const zExceptionUpsertRequest = zException.and(z.object({
    id: z.optional(z.int())
}));

export const zExceptionResponse = zExceptionUpsertRequest.and(z.object({
    created_by_name: z.optional(z.string())
}));

export const zTerminal = z.object({
    id: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    name: z.optional(z.string()),
    activation_code: z.optional(z.string()),
    branch_id: z.optional(z.int()),
    slug: z.optional(z.string()),
    status: z.optional(z.enum([
        'pending',
        'active',
        'revoked'
    ]))
});

export const zAuthTypes = z.object({
    id: z.optional(z.int()),
    name: z.optional(z.enum([
        'face',
        'fingerprint',
        'card'
    ]))
});

/**
 * This defines the type of auth supported by the terminal
 */
export const zTerminalCapabilities = z.object({
    auth_type_id: z.int(),
    auth_step: z.int()
});

/**
 * groups/subgroups allowed to auth at this terminal
 */
export const zTerminalAccessPolicy = z.object({
    group_id: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    subgroup_id: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    auth_type_id: z.optional(z.int())
});

export const zTerminalCreate = z.object({
    terminalDetails: z.optional(zTerminal.and(z.record(z.string(), z.unknown()))),
    authCapabilities: z.optional(z.array(zTerminalCapabilities)),
    authPolicies: z.optional(z.array(zTerminalAccessPolicy))
});

export const zTerminalUpsertResponse = zTerminal.and(z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    activationCode: z.optional(z.string())
}));

export const zTerminalFetchResponse = z.object({
    id: z.int(),
    name: z.string(),
    branch_id: z.int(),
    slug: z.optional(z.string()),
    branch: z.string(),
    status: z.enum(['active', 'inactive']),
    ip_address: z.union([
        z.string(),
        z.null()
    ]),
    last_heartbeat: z.union([
        z.iso.datetime(),
        z.null()
    ]),
    health_status: z.string(),
    auth_capabilities: z.optional(z.array(zTerminalCapabilities.and(z.object({
        terminal_id: z.optional(z.int()),
        auth_type_name: z.optional(z.enum([
            'face',
            'fingerprint',
            'card'
        ]))
    })))),
    access_policy: z.optional(z.array(zTerminalAccessPolicy.and(z.object({
        id: z.optional(z.int()),
        terminal_id: z.optional(z.int()),
        created_at: z.optional(z.iso.datetime()),
        updated_at: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        group_name: z.optional(z.string()),
        auth_type_name: z.optional(z.enum([
            'face',
            'fingerprint',
            'card'
        ]))
    }))))
});

export const zApiResponseTerminalList = z.object({
    success: z.boolean(),
    data: z.array(zTerminalFetchResponse)
});

export const zBiometricFaceEnrollRequest = z.object({
    user_id: z.int(),
    face_image: z.string()
});

export const zBiometricFaceEnrollResponse = z.object({
    message: z.string(),
    biometric_profile_id: z.int()
});

export const zBiometricFaceVerifyRequest = z.object({
    terminal_id: z.int(),
    face_image: z.string()
});

export const zBiometricFaceVerifyResponse = z.object({
    matched: z.boolean(),
    user_id: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    confidence_score: z.optional(z.number()),
    message: z.optional(z.string())
});

export const zAttendanceStatus = z.object({
    name: z.optional(z.enum([
        'present',
        'absent',
        'late',
        'on permission'
    ]))
});

/**
 * track progress throughout the auth sequence
 */
export const zTerminalAuthSession = z.object({
    user_id: z.optional(z.int()),
    terminal_id: z.optional(z.int()),
    current_step: z.optional(z.int()).default(1),
    status: z.optional(z.enum(['in_progress', 'completed']))
});

/**
 * logs each auth attemp, ie record is created for each completed auth session
 */
export const zTerminalAuthLog = z.object({
    user_id: z.optional(z.int()),
    terminal_id: z.optional(z.int()),
    attendance_context: z.optional(z.enum(['daily', 'event'])),
    event_id: z.optional(z.int()),
    auth_type_id: z.optional(z.int())
});

/**
 * Represents attendance after auth successs
 * ie upon successfull checkin and checkout for daily attendance
 * or checkin and/or checkout for event attendance depending on the handshake
 *
 */
export const zTerminalAttendanceSession = z.object({
    user_id: z.optional(z.int()),
    terminal_id: z.optional(z.int()),
    attendance_context: z.optional(z.enum(['daily', 'event'])),
    event_id: z.optional(z.int()),
    checkin_timestamp: z.optional(z.iso.datetime()),
    checkout_timestamp: z.optional(z.iso.datetime()),
    checkin_status: z.optional(z.enum(['on time', 'late'])),
    checkout_status: z.optional(z.enum(['on time', 'early'])),
    session_status: z.optional(z.enum([
        'active',
        'completed',
        'missed checkout'
    ])),
    sync_status: z.optional(z.enum([
        'pending',
        'synced',
        'error'
    ]))
});

/**
 * Summary of the daily/event attendance, this is the record that get sync to the central db
 * Was the user present, late or on permission for this day
 *
 */
export const zTerminalAttendanceSummary = z.object({
    user_id: z.optional(z.int()),
    terminal_id: z.optional(z.int()),
    attendance_date: z.optional(z.iso.date()),
    attendance_context: z.optional(z.enum(['daily', 'event'])),
    event_id: z.optional(z.int()),
    first_checkin: z.optional(z.iso.datetime()),
    last_checkout: z.optional(z.iso.datetime()),
    total_hours: z.optional(z.int()),
    attendance_status: z.optional(z.int()),
    derived_from_session: z.optional(z.boolean())
});

export const zTerminalAuthCreate = zTerminalAuthSession.and(z.object({
    terminal_auth_log: z.optional(zTerminalAuthLog.and(z.record(z.string(), z.unknown())))
}));

export const zTerminalAuthInProgressResponse = z.object({
    status: z.enum(['in_progress']),
    current_step: z.int(),
    next_auth_type_id: z.int()
});

export const zTerminalAuthCompletedResponse = z.object({
    status: z.enum(['completed']),
    message: z.optional(z.string()),
    attendance_session: zTerminalAttendanceSession
});

export const zTerminalAttendanceSummaryCreate = zTerminalAttendanceSummary.and(z.record(z.string(), z.unknown()));

export const zLogEntry = z.object({
    id: z.optional(z.int()),
    category: z.optional(z.string()),
    log_level: z.optional(z.string()),
    description: z.optional(z.string()),
    ip_address: z.optional(z.ipv4()),
    request_uri: z.optional(z.string()),
    context_data: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ])),
    date_created: z.optional(z.iso.datetime()),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    role_name: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zLoginData = z.object({
    body: zLogin,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * successful login
 */
export const zLoginResponse2 = zLoginResponse;

export const zLogoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * logout successful
 */
export const zLogoutResponse = z.object({
    success: z.optional(z.boolean())
});

export const zRefreshData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * refresh access token
 */
export const zRefreshResponse = zLoginResponse;

export const zListUsersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        user_type: z.optional(zUserType),
        status: z.optional(zUserStatus)
    }))
});

/**
 * List of users
 */
export const zListUsersResponse = z.array(zUserResponse);

export const zCreateUserData = z.object({
    body: zUserCreate,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * User created successfully
 */
export const zCreateUserResponse = zUserResponse;

export const zSyncUsersData = z.object({
    body: zSyncRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Users synced successfully
 */
export const zSyncUsersResponse = zSyncResponse;

export const zDeleteUserData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

export const zGetUserByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * User found
 */
export const zGetUserByIdResponse = zUserResponse;

export const zUpdateUserData = z.object({
    body: zUserCreate,
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * User updated successfully
 */
export const zUpdateUserResponse = zUserResponse;

export const zListRolesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Roles list
 */
export const zListRolesResponse = z.array(zRoleResponse);

export const zListBranchesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * List of branches
 */
export const zListBranchesResponse = z.array(zBranchResponse);

export const zCreateBranchData = z.object({
    body: zBranch.and(z.object({
        user_id: z.optional(z.int())
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Branch created successfully
 */
export const zCreateBranchResponse = zBranchResponse;

export const zUpdateBranchData = z.object({
    body: z.optional(zBranch.and(z.object({
        user_id: z.optional(z.int())
    }))),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

export const zCreateGroupTypeData = z.object({
    body: z.object({
        name: z.string(),
        abbreviation: z.optional(z.string())
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zListGroupsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Groups list
 */
export const zListGroupsResponse = z.array(zGroupResponse);

export const zCreateGroupData = z.object({
    body: zGroup,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAssignUsersToGroupData = z.object({
    body: z.optional(z.object({
        group_id: z.optional(z.int()),
        user_ids: z.optional(z.array(z.int()))
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zListSubgroupsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        groupId: z.int()
    }),
    query: z.optional(z.never())
});

export const zCreateSubgroupData = z.object({
    body: z.optional(zSubgroup),
    path: z.object({
        groupId: z.int()
    }),
    query: z.optional(z.never())
});

export const zAssignUsersToSubgroupData = z.object({
    body: z.optional(z.object({
        subgroup_id: z.optional(z.int()),
        user_ids: z.optional(z.array(z.int()))
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zFetchOnePermissionData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        id: z.int()
    })
});

/**
 * Details successfully retrieved.
 */
export const zFetchOnePermissionResponse = z.object({
    success: z.optional(z.boolean()),
    data: z.optional(zPermissionDetail)
});

export const zUpsertPermissionData = z.object({
    body: z.object({
        id: z.optional(z.union([
            z.int(),
            z.null()
        ])),
        permission_type_id: z.int(),
        user_id: z.int(),
        initiatedby: z.optional(z.union([
            z.int(),
            z.null()
        ])),
        reason: z.optional(z.string()),
        start_date: z.iso.date(),
        end_date: z.iso.date(),
        status: z.optional(z.enum([
            'pending',
            'approved',
            'rejected'
        ])),
        additional_proof: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Request processed successfully.
 */
export const zUpsertPermissionResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string())
});

export const zDeleteApiV1PermissionsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Permission request canceled and removed successfully.
 */
export const zDeleteApiV1PermissionsByIdResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string())
});

export const zGetApiV1PermissionsAllData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        search: z.optional(z.string()),
        status: z.optional(z.enum([
            'pending',
            'approved',
            'rejected'
        ])),
        page: z.optional(z.int()).default(1),
        limit: z.optional(z.int()).default(10)
    }))
});

/**
 * Array listing and metadata metrics maps generated.
 */
export const zGetApiV1PermissionsAllResponse = z.object({
    success: z.optional(z.boolean()),
    meta: z.optional(z.object({
        total_records: z.optional(z.int()),
        total_pages: z.optional(z.int()),
        current_page: z.optional(z.int()),
        limit: z.optional(z.int())
    })),
    data: z.optional(z.array(zPermissionExtendedRow))
});

export const zPostApiV1PermissionsReviewData = z.object({
    body: z.object({
        permission_id: z.int(),
        approver_id: z.int(),
        status: z.enum(['approved', 'rejected']),
        remark: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Operational state securely shifted.
 */
export const zPostApiV1PermissionsReviewResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string())
});

export const zListAnnouncementsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        group_id: z.optional(z.int()),
        subgroup_id: z.optional(z.int())
    }))
});

/**
 * List of events (optionally filtered by group or subgroup)
 */
export const zListAnnouncementsResponse = z.array(zAnnouncementResponse);

export const zCreateAnnouncementData = z.object({
    body: zAnnoucement.and(z.object({
        group_id: z.array(z.int()),
        subgroup_id: z.array(z.int())
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zListEventsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        group_id: z.optional(z.int()),
        subgroup_id: z.optional(z.int())
    }))
});

/**
 * List of events (optionally filtered by group or subgroup)
 */
export const zListEventsResponse = z.array(zEventResponse);

export const zCreateEventData = z.object({
    body: zEventCreate,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zDeleteEventData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

export const zOneExceptionData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        id: z.int()
    })
});

/**
 * List of exceptions
 */
export const zOneExceptionResponse = z.array(zExceptionResponse);

export const zCreateExceptionData = z.object({
    body: zExceptionUpsertRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Exception created successfully
 */
export const zCreateExceptionResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string())
});

export const zListExceptionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        exception_type: z.optional(z.enum([
            'public_holiday',
            'company_event',
            'system_maintenance',
            'emergency_closure',
            'term_closure',
            'other'
        ]))
    }))
});

/**
 * List of exceptions
 */
export const zListExceptionsResponse = z.object({
    success: z.optional(z.boolean()),
    data: z.optional(z.array(zExceptionResponse))
});

export const zDeleteExceptionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Exception deleted successfully
 */
export const zDeleteExceptionResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string())
});

export const zListTerminalsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        branch_id: z.optional(z.int()),
        terminal_id: z.optional(z.int()),
        status: z.optional(z.enum([
            'active',
            'pending',
            'revoked'
        ]))
    }))
});

/**
 * List of all terminals at that branch
 */
export const zListTerminalsResponse = zApiResponseTerminalList;

export const zCreateTerminalData = z.object({
    body: zTerminalCreate,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Terminal created successfully
 */
export const zCreateTerminalResponse = zTerminalUpsertResponse;

export const zUpdateTerminalData = z.object({
    body: zTerminalCreate,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Terminal created successfully
 */
export const zUpdateTerminalResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string())
});

export const zDeleteTerminalData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Delete terminal successfully
 */
export const zDeleteTerminalResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string())
});

export const zGetTerminalBySlugData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        slug: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Terminal details
 */
export const zGetTerminalBySlugResponse = zTerminalCreate;

export const zTerminalAuthData = z.object({
    body: zTerminalAuthCreate,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Authentication successful, if there are more auth types to complete, the response will indicate
 */
export const zTerminalAuthResponse = z.union([
    zTerminalAuthInProgressResponse,
    zTerminalAuthCompletedResponse
]);

export const zGetAttendanceLedgerData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        start_date: z.optional(z.iso.date()),
        end_date: z.optional(z.iso.date()),
        status: z.optional(z.string()),
        page: z.optional(z.int().gte(1)).default(1),
        limit: z.optional(z.int().gte(1).lte(50)).default(10),
        context: z.optional(z.enum(['daily', 'event'])),
        search: z.optional(z.string())
    }))
});

/**
 * Attendance matrix dataset generated successfully
 */
export const zGetAttendanceLedgerResponse = z.object({
    success: z.optional(z.boolean()),
    data: z.optional(zAttendanceLedgerData),
    meta: z.optional(zPaginationMeta)
});

export const zGetUserAttendanceAnalyticsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.object({
        context: z.optional(z.enum(['daily', 'event'])),
        start_date: z.optional(z.iso.date()),
        end_date: z.optional(z.iso.date()),
        page: z.optional(z.int()).default(1),
        limit: z.optional(z.int()).default(15)
    }))
});

/**
 * User analytics profile payload generated successfully.
 */
export const zGetUserAttendanceAnalyticsResponse = z.object({
    success: z.optional(z.boolean()),
    metrics: z.optional(z.object({
        expected_days: z.optional(z.int()),
        present_days: z.optional(z.int()),
        late_arrivals: z.optional(z.int()),
        absent_days: z.optional(z.int()),
        permission_days: z.optional(z.int())
    })),
    history: z.optional(z.array(z.object({
        date: z.optional(z.iso.date()),
        checkin: z.optional(z.union([
            z.iso.datetime(),
            z.null()
        ])),
        checkout: z.optional(z.union([
            z.iso.datetime(),
            z.null()
        ])),
        hours: z.optional(z.number()),
        status: z.optional(z.string()),
        terminal_id: z.optional(z.string()),
        sync_status: z.optional(z.string())
    }))),
    meta: z.optional(zPaginationMeta)
});

export const zPartialEditAttendanceData = z.object({
    body: z.object({
        id: z.int(),
        status: z.enum([
            'present',
            'absent',
            'on permission'
        ]),
        hours: z.number(),
        context: z.optional(z.enum(['daily', 'event'])),
        userId: z.optional(z.int()),
        date: z.optional(z.iso.date()),
        event_id: z.optional(z.union([
            z.int(),
            z.null()
        ]))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Attendance override was successful.
 */
export const zPartialEditAttendanceResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    userId: z.optional(z.int())
});

export const zSyncAttendanceSummaryData = z.object({
    body: z.array(zTerminalAttendanceSummaryCreate),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Attendance summary synced
 */
export const zSyncAttendanceSummaryResponse = z.union([
    z.object({
        message: z.optional(z.string())
    }),
    z.object({
        message: z.optional(z.string()),
        failed_records: z.optional(z.array(z.object({
            user_id: z.optional(z.int()),
            terminal_id: z.optional(z.int()),
            attendance_date: z.optional(z.iso.date()),
            attendance_context: z.optional(z.string()),
            attendance_status: z.optional(z.int()),
            error_message: z.optional(z.string())
        })))
    })
]);

export const zFaceEnrollmentData = z.object({
    body: zBiometricFaceEnrollRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * face enrollment successfull
 */
export const zFaceEnrollmentResponse = zBiometricFaceEnrollResponse;

export const zFaceVerificationData = z.object({
    body: zBiometricFaceVerifyRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * face verification result
 */
export const zFaceVerificationResponse = zBiometricFaceVerifyResponse;

export const zFetchLogsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        category: z.optional(z.enum([
            'system',
            'database',
            'error',
            'sync'
        ])),
        level: z.optional(z.enum([
            'info',
            'warning',
            'error'
        ])),
        start_date: z.optional(z.iso.date()),
        end_date: z.optional(z.iso.date()),
        page: z.optional(z.int().gte(1)).default(1),
        limit: z.optional(z.int().gte(1).lte(100)).default(50)
    }))
});

/**
 * Logs structural matrix payload successfully retrieved.
 */
export const zFetchLogsResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    meta: z.optional(z.object({
        total_records: z.optional(z.int()),
        total_pages: z.optional(z.int()),
        current_page: z.optional(z.int()),
        limit: z.optional(z.int())
    })),
    data: z.optional(z.array(zLogEntry))
});
