// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * FaceEnrollRequest
 */
export const zFaceEnrollRequest = z.object({
    user_id: z.int(),
    image: z.string()
});

/**
 * VerifyRequest
 */
export const zVerifyRequest = z.object({
    user_id: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    image: z.string()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.optional(z.unknown()),
    ctx: z.optional(z.record(z.string(), z.unknown()))
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

export const zHealthCheckHealthGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zEnrollFaceEnrollFacePostData = z.object({
    body: zFaceEnrollRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zVerifyFaceVerifyPostData = z.object({
    body: zVerifyRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});
