// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { assignUsersToGroup, assignUsersToSubgroup, createAnnouncement, createBranch, createEvent, createException, createGroup, createGroupType, createPermissionRequest, createSubgroup, createTerminal, createUser, decidePermissionRequest, deleteEvent, deleteException, deleteTerminal, deleteUser, faceEnrollment, faceVerification, getAttendanceLedger, getTerminalBySlug, getUserAttendanceAnalytics, getUserById, listAnnouncements, listBranches, listEvents, listExceptions, listGroups, listRoles, listSubgroups, listTerminals, listUsers, login, logout, oneException, type Options, refresh, syncAttendanceSummary, syncUsers, terminalAuth, updateBranch, updateTerminal, updateUser } from '../sdk.gen';
import type { AssignUsersToGroupData, AssignUsersToSubgroupData, CreateAnnouncementData, CreateBranchData, CreateBranchResponse, CreateEventData, CreateExceptionData, CreateExceptionResponse, CreateGroupData, CreateGroupTypeData, CreatePermissionRequestData, CreateSubgroupData, CreateTerminalData, CreateTerminalResponse, CreateUserData, CreateUserResponse, DecidePermissionRequestData, DeleteEventData, DeleteExceptionData, DeleteExceptionResponse, DeleteTerminalData, DeleteTerminalResponse, DeleteUserData, FaceEnrollmentData, FaceEnrollmentResponse, FaceVerificationData, FaceVerificationResponse, GetAttendanceLedgerData, GetAttendanceLedgerResponse, GetTerminalBySlugData, GetTerminalBySlugResponse, GetUserAttendanceAnalyticsData, GetUserAttendanceAnalyticsResponse, GetUserByIdData, GetUserByIdResponse, ListAnnouncementsData, ListAnnouncementsResponse, ListBranchesData, ListBranchesResponse, ListEventsData, ListEventsResponse, ListExceptionsData, ListExceptionsResponse, ListGroupsData, ListGroupsResponse, ListRolesData, ListRolesResponse, ListSubgroupsData, ListTerminalsData, ListTerminalsResponse, ListUsersData, ListUsersResponse, LoginData, LoginResponse2, LogoutData, LogoutResponse, OneExceptionData, OneExceptionResponse, RefreshData, RefreshResponse, SyncAttendanceSummaryData, SyncAttendanceSummaryResponse, SyncUsersData, SyncUsersResponse, TerminalAuthData, TerminalAuthResponse, UpdateBranchData, UpdateTerminalData, UpdateTerminalResponse, UpdateUserData, UpdateUserResponse } from '../types.gen';

/**
 * login admin users
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse2, AxiosError<DefaultError>, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse2, AxiosError<DefaultError>, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * logou admin users
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * refresh access token
 */
export const refreshMutation = (options?: Partial<Options<RefreshData>>): UseMutationOptions<RefreshResponse, AxiosError<DefaultError>, Options<RefreshData>> => {
    const mutationOptions: UseMutationOptions<RefreshResponse, AxiosError<DefaultError>, Options<RefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listUsersQueryKey = (options?: Options<ListUsersData>) => createQueryKey('listUsers', options);

/**
 * List all users
 */
export const listUsersOptions = (options?: Options<ListUsersData>) => queryOptions<ListUsersResponse, AxiosError<DefaultError>, ListUsersResponse, ReturnType<typeof listUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listUsersQueryKey(options)
});

/**
 * Create a new user
 */
export const createUserMutation = (options?: Partial<Options<CreateUserData>>): UseMutationOptions<CreateUserResponse, AxiosError<DefaultError>, Options<CreateUserData>> => {
    const mutationOptions: UseMutationOptions<CreateUserResponse, AxiosError<DefaultError>, Options<CreateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Sync users from the online SSEC database
 */
export const syncUsersMutation = (options?: Partial<Options<SyncUsersData>>): UseMutationOptions<SyncUsersResponse, AxiosError<DefaultError>, Options<SyncUsersData>> => {
    const mutationOptions: UseMutationOptions<SyncUsersResponse, AxiosError<DefaultError>, Options<SyncUsersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await syncUsers({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a user
 */
export const deleteUserMutation = (options?: Partial<Options<DeleteUserData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserByIdQueryKey = (options: Options<GetUserByIdData>) => createQueryKey('getUserById', options);

/**
 * Get a user by ID
 */
export const getUserByIdOptions = (options: Options<GetUserByIdData>) => queryOptions<GetUserByIdResponse, AxiosError<DefaultError>, GetUserByIdResponse, ReturnType<typeof getUserByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserByIdQueryKey(options)
});

/**
 * Update a user
 */
export const updateUserMutation = (options?: Partial<Options<UpdateUserData>>): UseMutationOptions<UpdateUserResponse, AxiosError<DefaultError>, Options<UpdateUserData>> => {
    const mutationOptions: UseMutationOptions<UpdateUserResponse, AxiosError<DefaultError>, Options<UpdateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRolesQueryKey = (options?: Options<ListRolesData>) => createQueryKey('listRoles', options);

/**
 * List all roles
 */
export const listRolesOptions = (options?: Options<ListRolesData>) => queryOptions<ListRolesResponse, AxiosError<DefaultError>, ListRolesResponse, ReturnType<typeof listRolesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRoles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRolesQueryKey(options)
});

export const listBranchesQueryKey = (options?: Options<ListBranchesData>) => createQueryKey('listBranches', options);

/**
 * List all branchs
 */
export const listBranchesOptions = (options?: Options<ListBranchesData>) => queryOptions<ListBranchesResponse, AxiosError<DefaultError>, ListBranchesResponse, ReturnType<typeof listBranchesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBranches({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBranchesQueryKey(options)
});

/**
 * Create a new branch
 *
 * Creat a new branch or campus within the institution
 */
export const createBranchMutation = (options?: Partial<Options<CreateBranchData>>): UseMutationOptions<CreateBranchResponse, AxiosError<DefaultError>, Options<CreateBranchData>> => {
    const mutationOptions: UseMutationOptions<CreateBranchResponse, AxiosError<DefaultError>, Options<CreateBranchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createBranch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update branch details
 */
export const updateBranchMutation = (options?: Partial<Options<UpdateBranchData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UpdateBranchData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UpdateBranchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateBranch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create a group type
 */
export const createGroupTypeMutation = (options?: Partial<Options<CreateGroupTypeData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateGroupTypeData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateGroupTypeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createGroupType({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listGroupsQueryKey = (options?: Options<ListGroupsData>) => createQueryKey('listGroups', options);

/**
 * List all groups
 */
export const listGroupsOptions = (options?: Options<ListGroupsData>) => queryOptions<ListGroupsResponse, AxiosError<DefaultError>, ListGroupsResponse, ReturnType<typeof listGroupsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listGroups({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listGroupsQueryKey(options)
});

/**
 * Create a group (class / department)
 */
export const createGroupMutation = (options?: Partial<Options<CreateGroupData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateGroupData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateGroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createGroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Assign users to a group
 */
export const assignUsersToGroupMutation = (options?: Partial<Options<AssignUsersToGroupData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AssignUsersToGroupData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AssignUsersToGroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await assignUsersToGroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listSubgroupsQueryKey = (options: Options<ListSubgroupsData>) => createQueryKey('listSubgroups', options);

/**
 * List subgroups under a group
 */
export const listSubgroupsOptions = (options: Options<ListSubgroupsData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof listSubgroupsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listSubgroups({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listSubgroupsQueryKey(options)
});

/**
 * Create a subgroup
 */
export const createSubgroupMutation = (options?: Partial<Options<CreateSubgroupData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateSubgroupData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateSubgroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createSubgroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Assign users to a subgroup
 */
export const assignUsersToSubgroupMutation = (options?: Partial<Options<AssignUsersToSubgroupData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AssignUsersToSubgroupData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AssignUsersToSubgroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await assignUsersToSubgroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create permission request for a user
 */
export const createPermissionRequestMutation = (options?: Partial<Options<CreatePermissionRequestData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreatePermissionRequestData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreatePermissionRequestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPermissionRequest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Approve or reject a permission request
 */
export const decidePermissionRequestMutation = (options?: Partial<Options<DecidePermissionRequestData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DecidePermissionRequestData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DecidePermissionRequestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await decidePermissionRequest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listAnnouncementsQueryKey = (options?: Options<ListAnnouncementsData>) => createQueryKey('listAnnouncements', options);

/**
 * Get all announcements or filter by group or subgroup ID
 */
export const listAnnouncementsOptions = (options?: Options<ListAnnouncementsData>) => queryOptions<ListAnnouncementsResponse, AxiosError<DefaultError>, ListAnnouncementsResponse, ReturnType<typeof listAnnouncementsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAnnouncements({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAnnouncementsQueryKey(options)
});

/**
 * Create an announcement
 */
export const createAnnouncementMutation = (options?: Partial<Options<CreateAnnouncementData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateAnnouncementData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateAnnouncementData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createAnnouncement({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listEventsQueryKey = (options?: Options<ListEventsData>) => createQueryKey('listEvents', options);

/**
 * Get all events or filter by group or subgroup ID
 */
export const listEventsOptions = (options?: Options<ListEventsData>) => queryOptions<ListEventsResponse, AxiosError<DefaultError>, ListEventsResponse, ReturnType<typeof listEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEventsQueryKey(options)
});

/**
 * Create an event
 */
export const createEventMutation = (options?: Partial<Options<CreateEventData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateEventData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateEventData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createEvent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete an event
 */
export const deleteEventMutation = (options?: Partial<Options<DeleteEventData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteEventData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteEventData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteEvent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const oneExceptionQueryKey = (options: Options<OneExceptionData>) => createQueryKey('oneException', options);

/**
 * Get exception with id as query param
 */
export const oneExceptionOptions = (options: Options<OneExceptionData>) => queryOptions<OneExceptionResponse, AxiosError<DefaultError>, OneExceptionResponse, ReturnType<typeof oneExceptionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await oneException({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: oneExceptionQueryKey(options)
});

/**
 * Create an exception
 */
export const createExceptionMutation = (options?: Partial<Options<CreateExceptionData>>): UseMutationOptions<CreateExceptionResponse, AxiosError<DefaultError>, Options<CreateExceptionData>> => {
    const mutationOptions: UseMutationOptions<CreateExceptionResponse, AxiosError<DefaultError>, Options<CreateExceptionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createException({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listExceptionsQueryKey = (options?: Options<ListExceptionsData>) => createQueryKey('listExceptions', options);

/**
 * List all exceptions
 */
export const listExceptionsOptions = (options?: Options<ListExceptionsData>) => queryOptions<ListExceptionsResponse, AxiosError<DefaultError>, ListExceptionsResponse, ReturnType<typeof listExceptionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listExceptions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listExceptionsQueryKey(options)
});

/**
 * Delete an exception
 */
export const deleteExceptionMutation = (options?: Partial<Options<DeleteExceptionData>>): UseMutationOptions<DeleteExceptionResponse, AxiosError<DefaultError>, Options<DeleteExceptionData>> => {
    const mutationOptions: UseMutationOptions<DeleteExceptionResponse, AxiosError<DefaultError>, Options<DeleteExceptionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteException({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listTerminalsQueryKey = (options?: Options<ListTerminalsData>) => createQueryKey('listTerminals', options);

/**
 * List all terminals at a particular branch
 */
export const listTerminalsOptions = (options?: Options<ListTerminalsData>) => queryOptions<ListTerminalsResponse, AxiosError<DefaultError>, ListTerminalsResponse, ReturnType<typeof listTerminalsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTerminals({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTerminalsQueryKey(options)
});

/**
 * create a terminal
 */
export const createTerminalMutation = (options?: Partial<Options<CreateTerminalData>>): UseMutationOptions<CreateTerminalResponse, AxiosError<DefaultError>, Options<CreateTerminalData>> => {
    const mutationOptions: UseMutationOptions<CreateTerminalResponse, AxiosError<DefaultError>, Options<CreateTerminalData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTerminal({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update an existing terminal
 */
export const updateTerminalMutation = (options?: Partial<Options<UpdateTerminalData>>): UseMutationOptions<UpdateTerminalResponse, AxiosError<DefaultError>, Options<UpdateTerminalData>> => {
    const mutationOptions: UseMutationOptions<UpdateTerminalResponse, AxiosError<DefaultError>, Options<UpdateTerminalData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateTerminal({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a terminal
 */
export const deleteTerminalMutation = (options?: Partial<Options<DeleteTerminalData>>): UseMutationOptions<DeleteTerminalResponse, AxiosError<DefaultError>, Options<DeleteTerminalData>> => {
    const mutationOptions: UseMutationOptions<DeleteTerminalResponse, AxiosError<DefaultError>, Options<DeleteTerminalData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteTerminal({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTerminalBySlugQueryKey = (options: Options<GetTerminalBySlugData>) => createQueryKey('getTerminalBySlug', options);

/**
 * Get terminal details by slug
 */
export const getTerminalBySlugOptions = (options: Options<GetTerminalBySlugData>) => queryOptions<GetTerminalBySlugResponse, AxiosError<DefaultError>, GetTerminalBySlugResponse, ReturnType<typeof getTerminalBySlugQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTerminalBySlug({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTerminalBySlugQueryKey(options)
});

/**
 * Authenticate at a terminal
 */
export const terminalAuthMutation = (options?: Partial<Options<TerminalAuthData>>): UseMutationOptions<TerminalAuthResponse, AxiosError<DefaultError>, Options<TerminalAuthData>> => {
    const mutationOptions: UseMutationOptions<TerminalAuthResponse, AxiosError<DefaultError>, Options<TerminalAuthData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await terminalAuth({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAttendanceLedgerQueryKey = (options?: Options<GetAttendanceLedgerData>) => createQueryKey('getAttendanceLedger', options);

/**
 * Retrieve the dense matrix attendance ledger grid
 *
 * Returns a paginated matrix of users alongside dense day-by-day attendance profiles, system exceptions, and column metadata matching the date filters.
 */
export const getAttendanceLedgerOptions = (options?: Options<GetAttendanceLedgerData>) => queryOptions<GetAttendanceLedgerResponse, AxiosError<DefaultError>, GetAttendanceLedgerResponse, ReturnType<typeof getAttendanceLedgerQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAttendanceLedger({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAttendanceLedgerQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getAttendanceLedgerInfiniteQueryKey = (options?: Options<GetAttendanceLedgerData>): QueryKey<Options<GetAttendanceLedgerData>> => createQueryKey('getAttendanceLedger', options, true);

/**
 * Retrieve the dense matrix attendance ledger grid
 *
 * Returns a paginated matrix of users alongside dense day-by-day attendance profiles, system exceptions, and column metadata matching the date filters.
 */
export const getAttendanceLedgerInfiniteOptions = (options?: Options<GetAttendanceLedgerData>) => infiniteQueryOptions<GetAttendanceLedgerResponse, AxiosError<DefaultError>, InfiniteData<GetAttendanceLedgerResponse>, QueryKey<Options<GetAttendanceLedgerData>>, number | Pick<QueryKey<Options<GetAttendanceLedgerData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetAttendanceLedgerData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getAttendanceLedger({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAttendanceLedgerInfiniteQueryKey(options)
});

export const getUserAttendanceAnalyticsQueryKey = (options: Options<GetUserAttendanceAnalyticsData>) => createQueryKey('getUserAttendanceAnalytics', options);

/**
 * Fetch Historical User Attendance Analytics Profile
 *
 * Returns chronological transactional log details alongside structural metric aggregates filtered by context.
 */
export const getUserAttendanceAnalyticsOptions = (options: Options<GetUserAttendanceAnalyticsData>) => queryOptions<GetUserAttendanceAnalyticsResponse, AxiosError<DefaultError>, GetUserAttendanceAnalyticsResponse, ReturnType<typeof getUserAttendanceAnalyticsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserAttendanceAnalytics({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserAttendanceAnalyticsQueryKey(options)
});

export const getUserAttendanceAnalyticsInfiniteQueryKey = (options: Options<GetUserAttendanceAnalyticsData>): QueryKey<Options<GetUserAttendanceAnalyticsData>> => createQueryKey('getUserAttendanceAnalytics', options, true);

/**
 * Fetch Historical User Attendance Analytics Profile
 *
 * Returns chronological transactional log details alongside structural metric aggregates filtered by context.
 */
export const getUserAttendanceAnalyticsInfiniteOptions = (options: Options<GetUserAttendanceAnalyticsData>) => infiniteQueryOptions<GetUserAttendanceAnalyticsResponse, AxiosError<DefaultError>, InfiniteData<GetUserAttendanceAnalyticsResponse>, QueryKey<Options<GetUserAttendanceAnalyticsData>>, number | Pick<QueryKey<Options<GetUserAttendanceAnalyticsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetUserAttendanceAnalyticsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getUserAttendanceAnalytics({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserAttendanceAnalyticsInfiniteQueryKey(options)
});

/**
 * Sync attendance summary to central database
 */
export const syncAttendanceSummaryMutation = (options?: Partial<Options<SyncAttendanceSummaryData>>): UseMutationOptions<SyncAttendanceSummaryResponse, AxiosError<DefaultError>, Options<SyncAttendanceSummaryData>> => {
    const mutationOptions: UseMutationOptions<SyncAttendanceSummaryResponse, AxiosError<DefaultError>, Options<SyncAttendanceSummaryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await syncAttendanceSummary({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Enroll face biometric profile
 */
export const faceEnrollmentMutation = (options?: Partial<Options<FaceEnrollmentData>>): UseMutationOptions<FaceEnrollmentResponse, AxiosError<DefaultError>, Options<FaceEnrollmentData>> => {
    const mutationOptions: UseMutationOptions<FaceEnrollmentResponse, AxiosError<DefaultError>, Options<FaceEnrollmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await faceEnrollment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Authenticate user via face recognition
 */
export const faceVerificationMutation = (options?: Partial<Options<FaceVerificationData>>): UseMutationOptions<FaceVerificationResponse, AxiosError<DefaultError>, Options<FaceVerificationData>> => {
    const mutationOptions: UseMutationOptions<FaceVerificationResponse, AxiosError<DefaultError>, Options<FaceVerificationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await faceVerification({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
